### ISSUE TITLE
Localhost is not opening after stop container

### ISSUE THREAD

**Issue by ricardo-moura** [mattrayner/docker-lamp#41]
hi guys,

I created a container with the following command (I'm using Windows):

winpty docker run -ti -p 8080:80 --name lamp1 -v //c/projects/lamp_5_6:/app -v //c/projects/lamp_5_6/mysql:/var/lib/mysql mattrayner/lamp:latest-1404-php5

It worked perfectly, however, when I need to stop and start it the localhost doesn't open anymore.

What can I do to it work again?

Thank you.

**Comment by mattrayner** [comment]
Hi @ricardo-moura, sorry for the delay in replying, I must have missed the notification for this 👎 

When you say it won't open any more, what do you mean? Do you mean Docker won't run the image, or that it is not accessible in your browser?

If you could provide the logs from your terminal, that would be  very helpful?

**Comment by ricardo-moura** [comment]
Hi @mattrayner,

How are you doing?

No worries.

Let me describe what happened:

When I ran the container for the first time I execute the following command:

**docker run -ti -p 8080:80 --name lamp1 -v //c/projects/lamp_5_6:/app mattra yner/lamp:latest-1404-php5**).

It works fine and I'm able to use the PHP and PHPMyAdmin.

My problems start when I need to turn off my computer.

Before turn off it, I stop my lamp1 container:

**docker stop lamp1**

When I turn on my computer I try to use the same container, so, I execute:

**docker start lamp1**

After starting the container, the localhost of lamp1 container isn't displayed when I access http://localhost:8080/.

So, to have my functional environment again I need to run the following commands:

**docker rm $(docker ps -q -a)**

**docker run -ti -p 8080:80 --name lamp1 -v //c/projects/lamp_5_6:/app mattra yner/lamp:latest-1404-php5**

This is a problem because I waste a long time repeating this process every day.

How can I fix that?

Thank you.

**Comment by mattrayner** [comment]
Hi @ricardo-moura, I see - my understanding of docker start/stop/run is that in order to map ports to a container you need to use `docker run` each time.

If you are specifying volumes, you shouldn't need to name your docket image - changing instead to using docker-run each time with an anonymous image should fix this. Now you can use ctrl+c to close out of the instance and that will stop the machine.

```batch
winpty docker run -ti -p 8080:80 -v //c/projects/lamp_5_6:/app -v //c/projects/lamp_5_6/mysql:/var/lib/mysql mattrayner/lamp:latest-1404-php5
```

### Additional options
You can ask docker to restart a container if it fails, or after a machine reboot (ref: https://docs.docker.com/config/containers/start-containers-automatically/)

winpty docker run -ti --restart always -p 8080:80 -v //c/projects/lamp_5_6:/app -v //c/projects/lamp_5_6/mysql:/var/lib/mysql mattrayner/lamp:latest-1404-php5

You could also use something like docker compose if you didn't want to type this every time:

`docker-compose.yml`
```yaml
version: '3'
services:
  lamp:
    image: "mattrayner/lamp:latest-1404-php5"
    volumes:
     - //c/projects/lamp_5_6:/app
     - //c/projects/lamp_5_6/mysql:/var/lib/mysql
    ports:
     - "8080:80"
```

```batch
winpty docker-compose up
winpty docker-compose down
winpty docker-compose up
```

The above *should* work for your use case - I must admit though, I've not tested it on a windows machine to be sure

**Comment by ricardo-moura** [comment]
Hi @mattrayner,

I thought that I could create a container using the command `docker run`, `docker stop` and `docker start` and use it later.

My goal is to configure a lamp 5.6 environment and import some MySQL databases to it.

When restart my computer, I'd like to see my databases informations (persist the data).

With the command `winpty docker run -ti -p 8080:80 -v //c/projects/lamp_5_6:/app -v //c/projects/lamp_5_6/mysql:/var/lib/mysql mattrayner/lamp:latest-1404-php5` is possible to persist mysql data, right?

I tried to use the `docker-compose.yml` as you described however when I execute it nothing happens.

I google this problem and I found out this answer [https://bit.ly/2RdZFsA](https://bit.ly/2RdZFsA):

> If your Dockerfile doesn't do anything (for example a web server to listen on port 80), it will be discarded as soon as it finish running the instructions. Because Docker containers should be "ephemeral".


Do you have ideas how can I fix this?

Ps: I'm using docker on Windows (Executing it with gitbash).

**Comment by mattrayner** [comment]
I'm not sure why docker-compose didn't work, but the command in your comment should work
just re-run that command when you restart your computer and it should be back up

I'd recommend making the app folder to `//c/projects/lamp_5_6/app` or you might have issues because you're making the /mysql folder available to apache

Other than that, I **think** you should be fine

**Comment by ricardo-moura** [comment]
I'm surprised why the docker-compose didn't run.

I'll restart my computer and try it again.

I create the `//c/projects/lamp_5_6/app` folder.

I'll test your orientations and if I've new problems I let you know.

You can close this issue.

Thank you so much for your help @mattrayner.

**Comment by mattrayner** [comment]
You're more than welcome @ricardo-moura, good luck!
